=begin
#Tripletex API

OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'date'

module TripletexRubyClient
  class Employee
    attr_accessor :id

    attr_accessor :version

    attr_accessor :changes

    attr_accessor :url

    attr_accessor :first_name

    attr_accessor :last_name

    attr_accessor :display_name

    attr_accessor :employee_number

    attr_accessor :date_of_birth

    attr_accessor :email

    # The country of the mobile phone number. If not set, the country is derived as best as possible from phoneNumberMobile. NB! 8 digit numbers are assumed to be Norwegian.
    attr_accessor :phone_number_mobile_country

    attr_accessor :phone_number_mobile

    attr_accessor :phone_number_home

    attr_accessor :phone_number_work

    attr_accessor :national_identity_number

    attr_accessor :dnumber

    attr_accessor :international_id

    attr_accessor :bank_account_number

    # IBAN field
    attr_accessor :iban

    # Bic (swift) field
    attr_accessor :bic

    # Country of creditor bank field
    attr_accessor :creditor_bank_country_id

    # UsesAbroadPayment field. Determines if we should use domestic or abroad remittance. To be able to use abroad remittance, one has to: 1: have Autopay 2: have valid combination of the fields Iban, Bic (swift) and Country of creditor bank. 
    attr_accessor :uses_abroad_payment

    # Define the employee's user type.<br>STANDARD: Reduced access. Users with limited system entitlements.<br>EXTENDED: Users can be given all system entitlements.<br>NO_ACCESS: User with no log on access.<br>Users with access to Tripletex must confirm the email address.
    attr_accessor :user_type

    # Determines if salary information can be registered on the user including hours, travel expenses and employee expenses. The user may also be selected as a project member on projects.
    attr_accessor :allow_information_registration

    attr_accessor :is_contact

    attr_accessor :comments

    # Address tied to the employee
    attr_accessor :address

    attr_accessor :department

    # Employments tied to the employee
    attr_accessor :employments

    attr_accessor :holiday_allowance_earned

    attr_accessor :employee_category

    attr_accessor :is_auth_project_overview_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'version' => :'version',
        :'changes' => :'changes',
        :'url' => :'url',
        :'first_name' => :'firstName',
        :'last_name' => :'lastName',
        :'display_name' => :'displayName',
        :'employee_number' => :'employeeNumber',
        :'date_of_birth' => :'dateOfBirth',
        :'email' => :'email',
        :'phone_number_mobile_country' => :'phoneNumberMobileCountry',
        :'phone_number_mobile' => :'phoneNumberMobile',
        :'phone_number_home' => :'phoneNumberHome',
        :'phone_number_work' => :'phoneNumberWork',
        :'national_identity_number' => :'nationalIdentityNumber',
        :'dnumber' => :'dnumber',
        :'international_id' => :'internationalId',
        :'bank_account_number' => :'bankAccountNumber',
        :'iban' => :'iban',
        :'bic' => :'bic',
        :'creditor_bank_country_id' => :'creditorBankCountryId',
        :'uses_abroad_payment' => :'usesAbroadPayment',
        :'user_type' => :'userType',
        :'allow_information_registration' => :'allowInformationRegistration',
        :'is_contact' => :'isContact',
        :'comments' => :'comments',
        :'address' => :'address',
        :'department' => :'department',
        :'employments' => :'employments',
        :'holiday_allowance_earned' => :'holidayAllowanceEarned',
        :'employee_category' => :'employeeCategory',
        :'is_auth_project_overview_url' => :'isAuthProjectOverviewURL'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Integer',
        :'version' => :'Integer',
        :'changes' => :'Array<Change>',
        :'url' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'display_name' => :'String',
        :'employee_number' => :'String',
        :'date_of_birth' => :'String',
        :'email' => :'String',
        :'phone_number_mobile_country' => :'Country',
        :'phone_number_mobile' => :'String',
        :'phone_number_home' => :'String',
        :'phone_number_work' => :'String',
        :'national_identity_number' => :'String',
        :'dnumber' => :'String',
        :'international_id' => :'InternationalId',
        :'bank_account_number' => :'String',
        :'iban' => :'String',
        :'bic' => :'String',
        :'creditor_bank_country_id' => :'Integer',
        :'uses_abroad_payment' => :'BOOLEAN',
        :'user_type' => :'String',
        :'allow_information_registration' => :'BOOLEAN',
        :'is_contact' => :'BOOLEAN',
        :'comments' => :'String',
        :'address' => :'Address',
        :'department' => :'Department',
        :'employments' => :'Array<Employment>',
        :'holiday_allowance_earned' => :'HolidayAllowanceEarned',
        :'employee_category' => :'EmployeeCategory',
        :'is_auth_project_overview_url' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'version')
        self.version = attributes[:'version']
      end

      if attributes.has_key?(:'changes')
        if (value = attributes[:'changes']).is_a?(Array)
          self.changes = value
        end
      end

      if attributes.has_key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.has_key?(:'firstName')
        self.first_name = attributes[:'firstName']
      end

      if attributes.has_key?(:'lastName')
        self.last_name = attributes[:'lastName']
      end

      if attributes.has_key?(:'displayName')
        self.display_name = attributes[:'displayName']
      end

      if attributes.has_key?(:'employeeNumber')
        self.employee_number = attributes[:'employeeNumber']
      end

      if attributes.has_key?(:'dateOfBirth')
        self.date_of_birth = attributes[:'dateOfBirth']
      end

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.has_key?(:'phoneNumberMobileCountry')
        self.phone_number_mobile_country = attributes[:'phoneNumberMobileCountry']
      end

      if attributes.has_key?(:'phoneNumberMobile')
        self.phone_number_mobile = attributes[:'phoneNumberMobile']
      end

      if attributes.has_key?(:'phoneNumberHome')
        self.phone_number_home = attributes[:'phoneNumberHome']
      end

      if attributes.has_key?(:'phoneNumberWork')
        self.phone_number_work = attributes[:'phoneNumberWork']
      end

      if attributes.has_key?(:'nationalIdentityNumber')
        self.national_identity_number = attributes[:'nationalIdentityNumber']
      end

      if attributes.has_key?(:'dnumber')
        self.dnumber = attributes[:'dnumber']
      end

      if attributes.has_key?(:'internationalId')
        self.international_id = attributes[:'internationalId']
      end

      if attributes.has_key?(:'bankAccountNumber')
        self.bank_account_number = attributes[:'bankAccountNumber']
      end

      if attributes.has_key?(:'iban')
        self.iban = attributes[:'iban']
      end

      if attributes.has_key?(:'bic')
        self.bic = attributes[:'bic']
      end

      if attributes.has_key?(:'creditorBankCountryId')
        self.creditor_bank_country_id = attributes[:'creditorBankCountryId']
      end

      if attributes.has_key?(:'usesAbroadPayment')
        self.uses_abroad_payment = attributes[:'usesAbroadPayment']
      end

      if attributes.has_key?(:'userType')
        self.user_type = attributes[:'userType']
      end

      if attributes.has_key?(:'allowInformationRegistration')
        self.allow_information_registration = attributes[:'allowInformationRegistration']
      end

      if attributes.has_key?(:'isContact')
        self.is_contact = attributes[:'isContact']
      end

      if attributes.has_key?(:'comments')
        self.comments = attributes[:'comments']
      end

      if attributes.has_key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.has_key?(:'department')
        self.department = attributes[:'department']
      end

      if attributes.has_key?(:'employments')
        if (value = attributes[:'employments']).is_a?(Array)
          self.employments = value
        end
      end

      if attributes.has_key?(:'holidayAllowanceEarned')
        self.holiday_allowance_earned = attributes[:'holidayAllowanceEarned']
      end

      if attributes.has_key?(:'employeeCategory')
        self.employee_category = attributes[:'employeeCategory']
      end

      if attributes.has_key?(:'isAuthProjectOverviewURL')
        self.is_auth_project_overview_url = attributes[:'isAuthProjectOverviewURL']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @first_name.nil?
        invalid_properties.push('invalid value for "first_name", first_name cannot be nil.')
      end

      if @first_name.to_s.length > 100
        invalid_properties.push('invalid value for "first_name", the character length must be smaller than or equal to 100.')
      end

      if @first_name.to_s.length < 1
        invalid_properties.push('invalid value for "first_name", the character length must be great than or equal to 1.')
      end

      if @last_name.nil?
        invalid_properties.push('invalid value for "last_name", last_name cannot be nil.')
      end

      if @last_name.to_s.length > 100
        invalid_properties.push('invalid value for "last_name", the character length must be smaller than or equal to 100.')
      end

      if @last_name.to_s.length < 1
        invalid_properties.push('invalid value for "last_name", the character length must be great than or equal to 1.')
      end

      if !@employee_number.nil? && @employee_number.to_s.length > 100
        invalid_properties.push('invalid value for "employee_number", the character length must be smaller than or equal to 100.')
      end

      if !@employee_number.nil? && @employee_number.to_s.length < 0
        invalid_properties.push('invalid value for "employee_number", the character length must be great than or equal to 0.')
      end

      if !@email.nil? && @email.to_s.length > 100
        invalid_properties.push('invalid value for "email", the character length must be smaller than or equal to 100.')
      end

      if !@phone_number_mobile.nil? && @phone_number_mobile.to_s.length > 100
        invalid_properties.push('invalid value for "phone_number_mobile", the character length must be smaller than or equal to 100.')
      end

      if !@phone_number_home.nil? && @phone_number_home.to_s.length > 100
        invalid_properties.push('invalid value for "phone_number_home", the character length must be smaller than or equal to 100.')
      end

      if !@phone_number_work.nil? && @phone_number_work.to_s.length > 100
        invalid_properties.push('invalid value for "phone_number_work", the character length must be smaller than or equal to 100.')
      end

      if !@national_identity_number.nil? && @national_identity_number.to_s.length > 100
        invalid_properties.push('invalid value for "national_identity_number", the character length must be smaller than or equal to 100.')
      end

      if !@dnumber.nil? && @dnumber.to_s.length > 11
        invalid_properties.push('invalid value for "dnumber", the character length must be smaller than or equal to 11.')
      end

      if !@bank_account_number.nil? && @bank_account_number.to_s.length > 100
        invalid_properties.push('invalid value for "bank_account_number", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @first_name.nil?
      return false if @first_name.to_s.length > 100
      return false if @first_name.to_s.length < 1
      return false if @last_name.nil?
      return false if @last_name.to_s.length > 100
      return false if @last_name.to_s.length < 1
      return false if !@employee_number.nil? && @employee_number.to_s.length > 100
      return false if !@employee_number.nil? && @employee_number.to_s.length < 0
      return false if !@email.nil? && @email.to_s.length > 100
      return false if !@phone_number_mobile.nil? && @phone_number_mobile.to_s.length > 100
      return false if !@phone_number_home.nil? && @phone_number_home.to_s.length > 100
      return false if !@phone_number_work.nil? && @phone_number_work.to_s.length > 100
      return false if !@national_identity_number.nil? && @national_identity_number.to_s.length > 100
      return false if !@dnumber.nil? && @dnumber.to_s.length > 11
      return false if !@bank_account_number.nil? && @bank_account_number.to_s.length > 100
      user_type_validator = EnumAttributeValidator.new('String', ['STANDARD', 'EXTENDED', 'NO_ACCESS'])
      return false unless user_type_validator.valid?(@user_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      if first_name.nil?
        fail ArgumentError, 'first_name cannot be nil'
      end

      if first_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "first_name", the character length must be smaller than or equal to 100.'
      end

      if first_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "first_name", the character length must be great than or equal to 1.'
      end

      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      if last_name.nil?
        fail ArgumentError, 'last_name cannot be nil'
      end

      if last_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "last_name", the character length must be smaller than or equal to 100.'
      end

      if last_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "last_name", the character length must be great than or equal to 1.'
      end

      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_number Value to be assigned
    def employee_number=(employee_number)
      if !employee_number.nil? && employee_number.to_s.length > 100
        fail ArgumentError, 'invalid value for "employee_number", the character length must be smaller than or equal to 100.'
      end

      if !employee_number.nil? && employee_number.to_s.length < 0
        fail ArgumentError, 'invalid value for "employee_number", the character length must be great than or equal to 0.'
      end

      @employee_number = employee_number
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if !email.nil? && email.to_s.length > 100
        fail ArgumentError, 'invalid value for "email", the character length must be smaller than or equal to 100.'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number_mobile Value to be assigned
    def phone_number_mobile=(phone_number_mobile)
      if !phone_number_mobile.nil? && phone_number_mobile.to_s.length > 100
        fail ArgumentError, 'invalid value for "phone_number_mobile", the character length must be smaller than or equal to 100.'
      end

      @phone_number_mobile = phone_number_mobile
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number_home Value to be assigned
    def phone_number_home=(phone_number_home)
      if !phone_number_home.nil? && phone_number_home.to_s.length > 100
        fail ArgumentError, 'invalid value for "phone_number_home", the character length must be smaller than or equal to 100.'
      end

      @phone_number_home = phone_number_home
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number_work Value to be assigned
    def phone_number_work=(phone_number_work)
      if !phone_number_work.nil? && phone_number_work.to_s.length > 100
        fail ArgumentError, 'invalid value for "phone_number_work", the character length must be smaller than or equal to 100.'
      end

      @phone_number_work = phone_number_work
    end

    # Custom attribute writer method with validation
    # @param [Object] national_identity_number Value to be assigned
    def national_identity_number=(national_identity_number)
      if !national_identity_number.nil? && national_identity_number.to_s.length > 100
        fail ArgumentError, 'invalid value for "national_identity_number", the character length must be smaller than or equal to 100.'
      end

      @national_identity_number = national_identity_number
    end

    # Custom attribute writer method with validation
    # @param [Object] dnumber Value to be assigned
    def dnumber=(dnumber)
      if !dnumber.nil? && dnumber.to_s.length > 11
        fail ArgumentError, 'invalid value for "dnumber", the character length must be smaller than or equal to 11.'
      end

      @dnumber = dnumber
    end

    # Custom attribute writer method with validation
    # @param [Object] bank_account_number Value to be assigned
    def bank_account_number=(bank_account_number)
      if !bank_account_number.nil? && bank_account_number.to_s.length > 100
        fail ArgumentError, 'invalid value for "bank_account_number", the character length must be smaller than or equal to 100.'
      end

      @bank_account_number = bank_account_number
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] user_type Object to be assigned
    def user_type=(user_type)
      validator = EnumAttributeValidator.new('String', ['STANDARD', 'EXTENDED', 'NO_ACCESS'])
      unless validator.valid?(user_type)
        fail ArgumentError, 'invalid value for "user_type", must be one of #{validator.allowable_values}.'
      end
      @user_type = user_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          version == o.version &&
          changes == o.changes &&
          url == o.url &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          display_name == o.display_name &&
          employee_number == o.employee_number &&
          date_of_birth == o.date_of_birth &&
          email == o.email &&
          phone_number_mobile_country == o.phone_number_mobile_country &&
          phone_number_mobile == o.phone_number_mobile &&
          phone_number_home == o.phone_number_home &&
          phone_number_work == o.phone_number_work &&
          national_identity_number == o.national_identity_number &&
          dnumber == o.dnumber &&
          international_id == o.international_id &&
          bank_account_number == o.bank_account_number &&
          iban == o.iban &&
          bic == o.bic &&
          creditor_bank_country_id == o.creditor_bank_country_id &&
          uses_abroad_payment == o.uses_abroad_payment &&
          user_type == o.user_type &&
          allow_information_registration == o.allow_information_registration &&
          is_contact == o.is_contact &&
          comments == o.comments &&
          address == o.address &&
          department == o.department &&
          employments == o.employments &&
          holiday_allowance_earned == o.holiday_allowance_earned &&
          employee_category == o.employee_category &&
          is_auth_project_overview_url == o.is_auth_project_overview_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, version, changes, url, first_name, last_name, display_name, employee_number, date_of_birth, email, phone_number_mobile_country, phone_number_mobile, phone_number_home, phone_number_work, national_identity_number, dnumber, international_id, bank_account_number, iban, bic, creditor_bank_country_id, uses_abroad_payment, user_type, allow_information_registration, is_contact, comments, address, department, employments, holiday_allowance_earned, employee_category, is_auth_project_overview_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TripletexRubyClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
