=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::BankreconciliationmatchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BankreconciliationmatchApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::BankreconciliationmatchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BankreconciliationmatchApi' do
    it 'should create an instance of BankreconciliationmatchApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::BankreconciliationmatchApi)
    end
  end

  # unit tests for delete
  # [BETA] Delete a bank reconciliation match by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # [BETA] Get bank reconciliation match by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperBankReconciliationMatch]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post
  # [BETA] Create a bank reconciliation match.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [BankReconciliationMatch] :body Partial object describing what should be updated
  # @return [ResponseWrapperBankReconciliationMatch]
  describe 'post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # [BETA] Update a bank reconciliation match by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [BankReconciliationMatch] :body Partial object describing what should be updated
  # @return [ResponseWrapperBankReconciliationMatch]
  describe 'put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search
  # [BETA] Find bank reconciliation match corresponding with sent data.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id List of IDs
  # @option opts [String] :bank_reconciliation_id List of bank reconciliation IDs
  # @option opts [Integer] :count Number of elements to return
  # @option opts [Integer] :from From index
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseBankReconciliationMatch]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for suggest
  # [BETA] Suggest matches for a bank reconciliation by ID.
  # 
  # @param bank_reconciliation_id Element ID
  # @param [Hash] opts the optional parameters
  # @return [ListResponseBankReconciliationMatch]
  describe 'suggest test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
