=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::EmployeeemploymentleaveOfAbsenceTypeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmployeeemploymentleaveOfAbsenceTypeApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::EmployeeemploymentleaveOfAbsenceTypeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmployeeemploymentleaveOfAbsenceTypeApi' do
    it 'should create an instance of EmployeeemploymentleaveOfAbsenceTypeApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::EmployeeemploymentleaveOfAbsenceTypeApi)
    end
  end

  # unit tests for search
  # [BETA] Find all leave of absence type IDs.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseLeaveOfAbsenceType]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
