=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::InventorystocktakingproductlineApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InventorystocktakingproductlineApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::InventorystocktakingproductlineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InventorystocktakingproductlineApi' do
    it 'should create an instance of InventorystocktakingproductlineApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::InventorystocktakingproductlineApi)
    end
  end

  # unit tests for delete
  # [BETA] Delete product line.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # [BETA] Get product line by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperProductLine]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post
  # [BETA] Create product line. When creating several product lines, use /list for better performance.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [ProductLine] :body JSON representing the new object to be created. Should not have ID and version set.
  # @return [ResponseWrapperProductLine]
  describe 'post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # [BETA] Update product line.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [ProductLine] :body Partial object describing what should be updated
  # @return [ResponseWrapperProductLine]
  describe 'put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search
  # [BETA] Find all product lines by stocktaking ID.
  # 
  # @param stocktaking_id Equals
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseProductLine]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
