=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::LedgeraccountingPeriodApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LedgeraccountingPeriodApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::LedgeraccountingPeriodApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LedgeraccountingPeriodApi' do
    it 'should create an instance of LedgeraccountingPeriodApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::LedgeraccountingPeriodApi)
    end
  end

  # unit tests for get
  # Get accounting period by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperAccountingPeriod]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search
  # Find accounting periods corresponding with sent data.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id List of IDs
  # @option opts [Integer] :number_from From and including
  # @option opts [Integer] :number_to To and excluding
  # @option opts [String] :start_from From and including
  # @option opts [String] :start_to To and excluding
  # @option opts [String] :end_from From and including
  # @option opts [String] :end_to To and excluding
  # @option opts [Integer] :count Number of elements to return
  # @option opts [Integer] :from From index
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseAccountingPeriod]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
