=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::PurchaseOrdergoodsReceiptApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PurchaseOrdergoodsReceiptApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::PurchaseOrdergoodsReceiptApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PurchaseOrdergoodsReceiptApi' do
    it 'should create an instance of PurchaseOrdergoodsReceiptApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::PurchaseOrdergoodsReceiptApi)
    end
  end

  # unit tests for confirm
  # [BETA] Confirm goods receipt. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param id Purchase Order ID.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :create_rest_order Create restorder if quantity received is less than ordered
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperPurchaseOrder]
  describe 'confirm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # [BETA] Delete goods receipt by ID. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_by_ids
  # [BETA] Delete multiple goods receipt by ID. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param ids ID of the elements
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_by_ids test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # [BETA] Get goods receipt by purchase order ID. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperGoodsReceipt]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post
  # [BETA] Register goods receipt without an existing purchase order. When registration of several goods receipt, use /list for better performance. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [GoodsReceipt] :body JSON representing the new object to be created. Should not have ID and version set.
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperGoodsReceipt]
  describe 'post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_list
  # [BETA] Register multiple goods receipt without an existing purchase order. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<GoodsReceipt>] :body JSON representing a list of new object to be created. Should not have ID and version set.
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseGoodsReceipt]
  describe 'post_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # [BETA] Update goods receipt. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param id Goods Receipt ID.
  # @param [Hash] opts the optional parameters
  # @option opts [GoodsReceipt] :body Partial object describing what should be updated
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperGoodsReceipt]
  describe 'put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for receive_and_confirm
  # [BETA]  Receive all ordered products and approve goods receipt. Only available for users that have activated the Logistics/Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param id Purchase Order ID.
  # @param received_date The approval date for the subscription.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :inventory_id ID of inventory. Main inventory is set as default
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperPurchaseOrder]
  describe 'receive_and_confirm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for register_goods_receipt
  # [BETA] Register goods receipt. Quantity received on the products is set to the same as quantity ordered. To update the quantity received, use PUT /purchaseOrder/goodsReceiptLine/{id}. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param id Purchase Order ID.
  # @param registration_date yyyy-MM-dd. Defaults to today.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :inventory_id ID of inventory. Main inventory is set as default
  # @option opts [String] :comment Containing
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperGoodsReceipt]
  describe 'register_goods_receipt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search
  # [BETA] Get goods receipt. Only available for users that have activated the Logistics Plus Beta-program in &#39;Our customer account&#39;
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :received_date_from Format is yyyy-MM-dd (from and incl.).
  # @option opts [String] :received_date_to Format is yyyy-MM-dd (to and incl.).
  # @option opts [String] :status Equals
  # @option opts [BOOLEAN] :without_purchase Equals
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseGoodsReceipt]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
