=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::SupplierApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SupplierApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::SupplierApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupplierApi' do
    it 'should create an instance of SupplierApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::SupplierApi)
    end
  end

  # unit tests for delete
  # [BETA] Delete supplier by ID
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Get supplier by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperSupplier]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post
  # Create supplier. Related supplier addresses may also be created.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Supplier] :body JSON representing the new object to be created. Should not have ID and version set.
  # @return [ResponseWrapperSupplier]
  describe 'post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_list
  # [BETA] Create multiple suppliers. Related supplier addresses may also be created.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Supplier>] :body JSON representing a list of new object to be created. Should not have ID and version set.
  # @return [ListResponseSupplier]
  describe 'post_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # Update supplier. 
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [Supplier] :body Partial object describing what should be updated
  # @return [ResponseWrapperSupplier]
  describe 'put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_list
  # [BETA] Update multiple suppliers. Addresses can also be updated.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Supplier>] :body JSON representing updates to object. Should have ID and version set.
  # @return [ListResponseSupplier]
  describe 'put_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search
  # Find suppliers corresponding with sent data.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id List of IDs
  # @option opts [String] :supplier_number List of IDs
  # @option opts [String] :organization_number Equals
  # @option opts [String] :email Equals
  # @option opts [String] :invoice_email Equals
  # @option opts [BOOLEAN] :is_inactive Equals
  # @option opts [String] :account_manager_id List of IDs
  # @option opts [String] :changed_since Only return elements that have changed since this date and time
  # @option opts [BOOLEAN] :is_wholesaler Equals
  # @option opts [BOOLEAN] :show_products Equals
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseSupplier]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
