=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::TimesheetmonthApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TimesheetmonthApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::TimesheetmonthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimesheetmonthApi' do
    it 'should create an instance of TimesheetmonthApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::TimesheetmonthApi)
    end
  end

  # unit tests for approve
  # approve month(s).  If id is provided the other args are ignored
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id Element ID
  # @option opts [String] :employee_ids List of IDs. Defaults to ID of token owner.
  # @option opts [String] :month_year 2020-01
  # @option opts [String] :approved_until_date yyyy-MM-dd. Defaults to today.. Defaults to end of month
  # @return [ListResponseMonthlyStatus]
  describe 'approve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for complete
  # complete month(s).  If id is provided the other args are ignored
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id Element ID
  # @option opts [String] :employee_ids List of IDs. Defaults to ID of token owner.
  # @option opts [String] :month_year 2020-01
  # @return [ListResponseMonthlyStatus]
  describe 'complete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Find monthly status entry by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperMonthlyStatus]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_by_month_number
  # Find monthly status for given month.
  # 
  # @param employee_ids List of IDs. Defaults to ID of token owner.
  # @param month_year 2020-01
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseMonthlyStatus]
  describe 'get_by_month_number test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reopen
  # reopen month(s).  If id is provided the other args are ignored
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id Element ID
  # @option opts [String] :employee_ids List of IDs. Defaults to ID of token owner.
  # @option opts [String] :month_year 2020-01
  # @return [ListResponseMonthlyStatus]
  describe 'reopen test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unapprove
  # unapprove month(s).  If id is provided the other args are ignored
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id Element ID
  # @option opts [String] :employee_ids List of IDs. Defaults to ID of token owner.
  # @option opts [String] :month_year 2020-01
  # @return [ListResponseMonthlyStatus]
  describe 'unapprove test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
