=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::VatReturnscommentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VatReturnscommentApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::VatReturnscommentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VatReturnscommentApi' do
    it 'should create an instance of VatReturnscommentApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::VatReturnscommentApi)
    end
  end

  # unit tests for all
  # [BETA] - Get all structured comments available
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseVatReturnsComment]
  describe 'all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for query
  # [BETA] - Get all structured comments related to a given vatCode
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :from From index
  # @option opts [Integer] :count Number of elements to return
  # @option opts [String] :sorting Sorting pattern
  # @option opts [String] :fields Fields filter pattern
  # @return [ListResponseVatReturnsVatCodeCommentDTO]
  describe 'query test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
