=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'

# Unit tests for TripletexRubyClient::VoucherApprovalListElementApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VoucherApprovalListElementApi' do
  before do
    # run before each test
    @instance = TripletexRubyClient::VoucherApprovalListElementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VoucherApprovalListElementApi' do
    it 'should create an instance of VoucherApprovalListElementApi' do
      expect(@instance).to be_instance_of(TripletexRubyClient::VoucherApprovalListElementApi)
    end
  end

  # unit tests for get
  # [BETA] Get by ID.
  # 
  # @param id Element ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Fields filter pattern
  # @return [ResponseWrapperVoucherApprovalListElement]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
