=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TripletexRubyClient::ResponseWrapperEmployeePreferences
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResponseWrapperEmployeePreferences' do
  before do
    # run before each test
    @instance = TripletexRubyClient::ResponseWrapperEmployeePreferences.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResponseWrapperEmployeePreferences' do
    it 'should create an instance of ResponseWrapperEmployeePreferences' do
      expect(@instance).to be_instance_of(TripletexRubyClient::ResponseWrapperEmployeePreferences)
    end
  end
  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
