=begin
#Tripletex API



OpenAPI spec version: 2.69.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.24

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TripletexRubyClient::VFProductOnboardingStatusDTO
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VFProductOnboardingStatusDTO' do
  before do
    # run before each test
    @instance = TripletexRubyClient::VFProductOnboardingStatusDTO.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VFProductOnboardingStatusDTO' do
    it 'should create an instance of VFProductOnboardingStatusDTO' do
      expect(@instance).to be_instance_of(TripletexRubyClient::VFProductOnboardingStatusDTO)
    end
  end
  describe 'test attribute "product_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "valid_from"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "valid_to"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "product_onboarding_status_last_change_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "onboarding_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NOT_STARTED", "STARTED", "SIGNING_STARTED", "IN_REVIEW", "ACCEPTED", "COMPLETED", "REJECTED", "CANCELED", "FAILED"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.onboarding_status = value }.not_to raise_error
      # end
    end
  end

end
